modLoader = "javafml"
loaderVersion = "[41,)"

license = "UNLICENSED"

[[mods]]
modId = "loadingbackgrounds"
version = "${version}"

displayName = "Loading Backgrounds"
displayURL = "https://legacy.curseforge.com/minecraft/mc-mods/loadingbackgrounds"

authors = "lupiiin_, luavixen <lua@foxgirl.dev> (https://foxgirl.dev/)"
description = "Custom loading screen backgrounds."

[[dependencies.trimeffects]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trimeffects]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
