modLoader = "javafml"
loaderVersion = "[1,)"

license = "UNLICENSED"

[[mods]]
modId = "loadingbackgrounds"
version = "${version}"

displayName = "Loading Backgrounds"
displayURL = "https://legacy.curseforge.com/minecraft/mc-mods/loadingbackgrounds"

authors = "lupiiin_, luavixen <lua@foxgirl.dev> (https://foxgirl.dev/)"
description = "Custom loading screen backgrounds."

[[mixins]]
config = "loadingbackgrounds.mixins.json"

[[dependencies.loadingbackgrounds]]
modId = "neoforge"
mandatory = true
versionRange = "[20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.loadingbackgrounds]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"
